# views.yaml
entities:
  County:
    view: PLAYGROUND.STYX.CHX_COUNTY_VW

  State:
    view: PLAYGROUND.STYX.CHX_STATE_VW

  StatePlane:
    view: PLAYGROUND.STYX.CHX_STATE_PLANE_VW

  Block:
    view: PLAYGROUND.STYX.CHX_BLOCK_VW
    
  BlockFormation:
    view: PLAYGROUND.STYX.CHX_BLOCK_FORMATION_VW

  BusinessUnit:
    view: PLAYGROUND.STYX.CHX_BUSINESS_UNIT_VW

  BusinessUnitCounty:
    view: PLAYGROUND.STYX.CHX_BUSINESS_UNIT_COUNTY_VW

  DevelopmentArea:
    view: PLAYGROUND.STYX.CHX_DEVELOPMENT_AREA_VW

  DevelopmentAreaFormation:
    view: PLAYGROUND.STYX.CHX_DEVELOPMENT_AREA_FORMATION_VW

  Formation:
    view: PLAYGROUND.STYX.CHX_FORMATION_VW

  Lateral:
    view: PLAYGROUND.STYX.CHX_LATERAL_VW

  RegulatoryField:
    view: PLAYGROUND.STYX.CHX_REGULATORY_FIELD_VW

  
